---
- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: boolean
    value: true
    state: present
  notify: restart finder

- name: Show file extensions in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllExtensions
    type: boolean
    value: true
    state: present
  notify: restart finder

- name: Show path bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: boolean
    value: true
    state: present
  notify: restart finder

- name: Show status bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: boolean
    value: true
    state: present
  notify: restart finder

- name: Disable "Empty trash" warning
  community.general.osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: boolean
    value: false
    state: present
  notify: restart finder

- name: Disable "Are you sure you want to open this application?" dialog
  community.general.osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: boolean
    value: false
    state: present

- name: Disable automatic capitalization
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: boolean
    value: false
    state: present

- name: Enable tap to click
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: boolean
    value: true
    state: present
  notify: restart systemuiserver

- name: Enable tap to click for current user
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1
    state: present
  notify: restart systemuiserver
