"$schema" = 'https://starship.rs/config-schema.json'

format = """
$line_break\
$time\
$python\
$terraform\
$aws\
$azure\
$kubernetes\
$directory\
$git_branch\
$git_status\
$line_break\
[â•‘](fg:color_blue2)\
$line_break\
[â•™â”€](fg:color_blue2)\
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#000000'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#635CC4'
dark_blue = '#2C2958'
color_blue2 = '#097E99'
dark_blue2 = '#033844'
color_blue3 = '#0a8caa'
color_blue4 = '#0a97aa'
color_aqua = '#089080'
dark_aqua = '#023933'
color_aqua2 = '#033933'
color_green = '#008b34'
color_purple = '#905CC4'
dark_purple = '#39244E'
color_pink = '#B45CC4'
dark_pink = '#5A2E62'
color_yellow = '#B49163'
dark_yellow = '#50402C'
color_red = '#d14c5a'
color_orange = '#B34B4F'
dark_orange = '#592527'

[os]
disabled = false
style = "bg:color_blue2 fg:dark_blue2"

[os.symbols]
Ubuntu = " ó°•ˆ "
Macos = " îœ‘ "
Linux = " ó°Œ½ "
Debian = " ó°£š "

[directory]
format = "[â•Ÿâ”€î‚¶](fg:color_blue2)[](fg:color_blue2)[ ï»  $path ](fg:dark_blue2 bg:color_blue2)[î‚´](fg:color_blue2)"
truncation_length = 3
truncation_symbol = ""

[git_branch]
format = '[â”€î‚¶](fg:color_aqua)[ ó°Š¤  $branch ](bg:color_aqua fg:dark_aqua)'

[git_status]
conflicted = 'ğŸ³ '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
up_to_date = ''
untracked = 'ğŸ¤· '
stashed = 'ğŸ“¦ '
modified = 'ğŸ“ '
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘… '
deleted = 'ğŸ—‘ '
format = '[$all_status$ahead_behind](bg:color_aqua fg:dark_aqua)[î‚´](fg:color_aqua)'

[aws]
format = "[â•Ÿâ”€î‚¶](fg:color_orange)[ ïƒ¯  $profile ](fg:dark_orange bg:color_orange)[](fg:color_orange)\n"
[aws.profile_aliases]
'prod/dp-uc-platform-use1-dev/AWS_UCI_CloudSupport_L2_PS' = 'CloudSupport'

[rust]
format = '[â•Ÿâ”€î‚¶](fg:color_pink)[ î¨ ( $version) ](fg:dark_pink bg:color_pink)][î‚´](fg:color_pink)'

[golang]
format = '[â•Ÿâ”€î‚¶](fg:color_pink)[ î˜§ ( $version) ](fg:dark_pink bg:color_pink)][î‚´](fg:color_pink)\n'

[java]
format = '[â•Ÿâ”€î‚¶](fg:color_pink)[ î‰– ( $version) ](fg:dark_pink bg:color_pink)[î‚´](bg:color_pink)\n'

[python]
format = "[â•Ÿâ”€î‚¶](fg:color_pink)[ î˜† ( $version) ](fg:dark_pink bg:color_pink)[î‚´](fg:color_pink)\n"

[terraform]
format = "[â•Ÿâ”€î‚¶](fg:color_purple)[ ó±¢ ( $workspace) ](fg:dark_purple bg:color_purple)[î‚´](fg:color_purple)\n"

[docker_context]
format = '[â•Ÿâ”€î‚¶](fg:color_blue)[ ó°¡¨ ( $context) ](fg:dark_blue bg:color_blue)][î‚´](fg:color_blue)'

[kubernetes]
disabled = false
format = "[â•Ÿâ”€î‚¶](fg:color_blue)[ ó±ƒ¾  $context $namespace ](fg:dark_blue bg:color_blue)[î‚´](fg:color_blue)\n"

[[kubernetes.contexts]]
context_pattern = "arn.*cluster/(?P<cluster>[\\w-]+)"
context_alias = "eks-$cluster"

[time]
disabled = false
time_format = "%R"
format = "[â•“â”€î‚¶](fg:color_yellow)[ ó°¥”  $time ](fg:dark_yellow bg:color_yellow)[î‚´](fg:color_yellow)\n"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ï„¸ ](fg:color_blue3)'
error_symbol = '[ï„¸ ](fg:color_yellow)'
vimcmd_symbol = '[ï´ ](bold fg:color_green)'
vimcmd_replace_one_symbol = '[ï´ ](bold fg:color_purple)'
vimcmd_replace_symbol = '[ï´ ](bold fg:color_purple)'
vimcmd_visual_symbol = '[ï´ ](bold fg:color_yellow)'
